 <!-- footer start here -->
 <div class="container-fluid text-responsive">
 <footer>
    <div class="footer-jumbotron text-responsive" >
            <p class="copyright" > Copyright &COPY;<?php echo date("Y")?> National Universities Commission</ 
          </div>
  </div>
 </footer>
</div>
<!-- CDN JQuery & JS -->
<script type="text/javascript" src="css/jquery-3.4.1.js"> </script>
<script type="text/javascript" src="css/bootstrap.js"> </script>

    </body>
</html>